development:
  adapter: postgresql
  encoding: utf8
  database: whatsapp-restaurant-bot-development
  pool: 5
  username: sacplus
  password: 1q2w3e4r5t

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: whatsapp-restaurant-bot_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: whatsapp-restaurant-bot_production
  pool: 5
  username:
  password: