development:
  adapter: postgresql
  encoding: utf8
  database: whatsapp-restaurant-bot_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: whatsapp-restaurant-bot_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: whatsapp-restaurant-bot_production
  pool: 5
  username:
  password: